services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules     # ホストの node_modules をマウントしないように
    environment:
      - CHOKIDAR_USEPOLLING=true 